import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F7F2EA",
  paper: "#FFFAF4",
  card: "rgba(255,255,255,0.82)",
  ink: "#17212B",
  muted: "#66707A",
  line: "rgba(23,33,43,0.08)",
  warm: "#F2E5D0",
  accent: "#143642",
  danger: "#B74343",
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  loadingSafe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingTitle: {
    marginTop: 16,
    fontSize: 22,
    fontWeight: "600",
    color: COLORS.ink,
  },
  authSafe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  authWrap: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 28,
    justifyContent: "space-between",
  },
  authTitle: {
    fontSize: 34,
    lineHeight: 42,
    fontWeight: "600",
    color: COLORS.ink,
    marginTop: 14,
  },
  authDescription: {
    marginTop: 14,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.muted,
  },
  authCard: {
    backgroundColor: COLORS.card,
    borderRadius: 28,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
  },
  switchRow: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 999,
    padding: 4,
    marginBottom: 8,
  },
  switchButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  switchButtonActive: {
    backgroundColor: COLORS.ink,
  },
  switchLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.muted,
  },
  switchLabelActive: {
    color: "#fff",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
    overflow: "hidden",
  },
  shellAura: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.65,
  },
  shellAuraTop: {
    width: 260,
    height: 260,
    top: -64,
    right: -72,
    backgroundColor: "rgba(214,198,255,0.55)",
  },
  shellAuraBottom: {
    width: 220,
    height: 220,
    top: 180,
    left: -96,
    backgroundColor: "rgba(255,221,190,0.28)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    backgroundColor: COLORS.card,
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    shadowColor: "#D9C7AE",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  wordmark: {
    fontSize: 11,
    letterSpacing: 3,
    color: "#8B6748",
  },
  headerTitle: {
    marginTop: 12,
    fontSize: 28,
    lineHeight: 35,
    fontWeight: "700",
    color: COLORS.ink,
  },
  headerSubtitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.muted,
  },
  content: {
    paddingTop: 14,
    paddingBottom: 110,
    gap: 14,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    gap: 14,
    shadowColor: "#D9C7AE",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: COLORS.ink,
  },
  tagButton: {
    backgroundColor: "rgba(243,228,207,0.95)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  tagButtonLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.ink,
  },
  ghostPill: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#fff",
  },
  ghostPillLabel: {
    fontSize: 12,
    color: COLORS.muted,
  },
  cover: {
    borderRadius: 26,
    overflow: "hidden",
    justifyContent: "space-between",
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    shadowColor: "#7B6A58",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 5,
  },
  coverLarge: {
    height: 188,
  },
  coverSmall: {
    height: 128,
  },
  coverAccent: {
    height: 4,
    borderRadius: 999,
    width: "42%",
  },
  coverGlow: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.7,
  },
  coverGlowTop: {
    width: 168,
    height: 168,
    top: -48,
    right: -30,
    opacity: 0.55,
  },
  coverTextWrap: {
    marginTop: "auto",
  },
  coverTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: COLORS.ink,
    textShadowColor: "rgba(255,255,255,0.18)",
    textShadowRadius: 12,
    textShadowOffset: { width: 0, height: 1 },
  },
  coverTitleLarge: {
    fontSize: 20,
    lineHeight: 26,
  },
  coverAuthor: {
    marginTop: 6,
    fontSize: 12,
    color: "rgba(23,33,43,0.62)",
  },
  bookTitle: {
    marginTop: 12,
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.ink,
  },
  bookTitleSmall: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.ink,
  },
  bookMeta: {
    marginTop: 4,
    fontSize: 15,
    color: COLORS.muted,
  },
  heroPrompt: {
    marginTop: 12,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.ink,
  },
  heroMetaLine: {
    marginTop: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.68)",
    fontSize: 12,
    color: "#7A746D",
  },
  caption: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.muted,
  },
  noteCard: {
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
  },
  notePreview: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: "500",
    color: COLORS.ink,
  },
  noteThought: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
  },
  noteMeta: {
    fontSize: 13,
    color: "#7A746D",
  },
  emptyState: {
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.ink,
    textAlign: "center",
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
    textAlign: "center",
  },
  primaryButton: {
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 4,
  },
  primaryButtonLabel: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  demoText: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.muted,
  },
  errorText: {
    fontSize: 13,
    color: COLORS.danger,
  },
  filterRow: {
    marginHorizontal: -2,
  },
  filterContent: {
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: COLORS.warm,
  },
  filterChipActive: {
    backgroundColor: COLORS.ink,
  },
  filterChipLabel: {
    fontSize: 13,
    color: COLORS.ink,
  },
  filterChipLabelActive: {
    color: "#fff",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  gridItem: {
    width: "47%",
  },
  recentBooksRow: {
    gap: 12,
    paddingRight: 8,
  },
  recentBookItem: {
    width: 164,
  },
  gridTitle: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  gridMeta: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.muted,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionSubhead: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.ink,
  },
  daysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dayCell: {
    width: "12.5%",
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  dayCellActive: {
    backgroundColor: COLORS.ink,
  },
  dayCellLabel: {
    fontSize: 13,
    color: COLORS.ink,
  },
  dayCellLabelActive: {
    color: "#fff",
  },
  dayCellEmpty: {
    width: "12.5%",
    minWidth: 40,
    height: 42,
  },
  dot: {
    marginTop: 6,
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  dotVisible: {
    backgroundColor: COLORS.accent,
  },
  dotSelected: {
    backgroundColor: "#EBCB96",
  },
  statRow: {
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  statValue: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.ink,
  },
  statLabel: {
    marginTop: 8,
    fontSize: 12,
    color: COLORS.muted,
  },
  menuRow: {
    backgroundColor: COLORS.paper,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 8,
  },
  menuLabel: {
    fontSize: 14,
    color: COLORS.ink,
  },
  bottomBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 14,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 28,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navButton: {
    flex: 1,
    alignItems: "center",
  },
  navLabel: {
    fontSize: 12,
    color: COLORS.muted,
  },
  navLabelActive: {
    color: COLORS.ink,
    fontWeight: "700",
  },
  plusButton: {
    width: 56,
    height: 56,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.accent,
    marginHorizontal: 4,
  },
  plusLabel: {
    fontSize: 28,
    lineHeight: 28,
    color: "#fff",
    fontWeight: "500",
  },
  overlayBackdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 28,
    backgroundColor: "rgba(23,33,43,0.32)",
  },
  overlayCard: {
    maxHeight: "86%",
    backgroundColor: "#fff",
    borderRadius: 34,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 28,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  overlayCompact: {
    maxHeight: "34%",
  },
  overlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  overlayTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: COLORS.ink,
  },
  overlayContent: {
    gap: 12,
    paddingBottom: 40,
  },
  overlayDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  input: {
    backgroundColor: COLORS.paper,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 14,
    color: COLORS.ink,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  textarea: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  listGap: {
    gap: 10,
  },
  searchResult: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    padding: 12,
    alignItems: "center",
  },
  searchCoverWrap: {
    width: 86,
  },
  statusRow: {
    backgroundColor: COLORS.paper,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusRowActive: {
    backgroundColor: COLORS.ink,
  },
  statusLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.ink,
  },
  statusLabelActive: {
    color: "#fff",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  primaryInlineButton: {
    flex: 1,
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  secondaryInlineButton: {
    flex: 1,
    backgroundColor: COLORS.paper,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  secondaryInlineLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  dangerInlineButton: {
    flex: 1,
    backgroundColor: COLORS.danger,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  miniActions: {
    flexDirection: "row",
    gap: 14,
    marginTop: 8,
  },
  miniAction: {
    fontSize: 12,
    color: COLORS.muted,
  },
  ratingRow: {
    flexDirection: "row",
    gap: 8,
  },
  ratingButton: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: COLORS.paper,
    alignItems: "center",
    paddingVertical: 12,
  },
  ratingButtonActive: {
    backgroundColor: COLORS.ink,
  },
  ratingLabel: {
    fontSize: 14,
    color: COLORS.ink,
    fontWeight: "600",
  },
  ratingLabelActive: {
    color: "#fff",
  },
  deleteButton: {
    borderWidth: 1,
    borderColor: "#EDC9C9",
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  deleteButtonLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.danger,
  },
  toastWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  toast: {
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  toastLabel: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
});
