import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F6EFE4",
  paper: "#FFF9F1",
  card: "rgba(255,255,255,0.78)",
  ink: "#17212B",
  muted: "#6F756F",
  line: "rgba(37,32,27,0.07)",
  warm: "#F3E4CF",
  accent: "#143642",
  danger: "#B74343",
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  loadingSafe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingTitle: {
    marginTop: 16,
    fontSize: 22,
    fontWeight: "600",
    color: COLORS.ink,
  },
  authSafe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  authWrap: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 28,
    justifyContent: "space-between",
  },
  authTitle: {
    fontSize: 34,
    lineHeight: 42,
    fontWeight: "600",
    color: COLORS.ink,
    marginTop: 14,
  },
  authDescription: {
    marginTop: 14,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.muted,
  },
  authCard: {
    backgroundColor: COLORS.card,
    borderRadius: 28,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
  },
  switchRow: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 999,
    padding: 4,
    marginBottom: 8,
  },
  switchButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  switchButtonActive: {
    backgroundColor: COLORS.ink,
  },
  switchLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.muted,
  },
  switchLabelActive: {
    color: "#fff",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
    overflow: "hidden",
  },
  wordmark: {
    fontSize: 11,
    letterSpacing: 3,
    color: "#8B6748",
  },
  shellAura: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.65,
  },
  shellAuraBottom: {
    width: 250,
    height: 250,
    top: 240,
    left: -112,
    backgroundColor: "rgba(255,219,187,0.28)",
  },
  content: {
    paddingTop: 12,
    paddingBottom: 118,
    gap: 18,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 34,
    padding: 1,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.52)",
    overflow: "hidden",
    shadowColor: "#D2C1A7",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  cardInner: {
    backgroundColor: "rgba(255,251,245,0.88)",
    borderRadius: 33,
    padding: 18,
    gap: 14,
  },
  cardOrb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.7,
  },
  cardOrbTop: {
    width: 170,
    height: 170,
    top: -60,
    right: -30,
    backgroundColor: "rgba(232,225,250,0.58)",
  },
  cardOrbBottom: {
    width: 140,
    height: 140,
    bottom: -78,
    left: -30,
    backgroundColor: "rgba(255,233,204,0.34)",
  },
  cardSheen: {
    position: "absolute",
    top: 20,
    right: 24,
    width: 92,
    height: 2,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.2,
    color: COLORS.ink,
  },
  tagButton: {
    backgroundColor: "rgba(244,229,206,0.92)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.58)",
  },
  tagButtonLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.ink,
  },
  cover: {
    borderRadius: 26,
    overflow: "hidden",
    justifyContent: "space-between",
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    shadowColor: "#7B6A58",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 5,
  },
  coverLarge: {
    height: 198,
  },
  coverSmall: {
    height: 128,
  },
  coverAccent: {
    height: 4,
    borderRadius: 999,
    width: "42%",
  },
  coverGlow: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.7,
  },
  coverGlowTop: {
    width: 168,
    height: 168,
    top: -48,
    right: -30,
    opacity: 0.55,
  },
  coverTextWrap: {
    marginTop: "auto",
  },
  coverTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    color: COLORS.ink,
    textShadowColor: "rgba(255,255,255,0.18)",
    textShadowRadius: 12,
    textShadowOffset: { width: 0, height: 1 },
  },
  coverTitleLarge: {
    fontSize: 20,
    lineHeight: 26,
  },
  coverAuthor: {
    marginTop: 6,
    fontSize: 12,
    color: "rgba(23,33,43,0.62)",
  },
  bookTitle: {
    marginTop: 12,
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.ink,
    letterSpacing: -0.4,
  },
  bookTitleSmall: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.ink,
  },
  bookMeta: {
    marginTop: 4,
    fontSize: 15,
    color: COLORS.muted,
  },
  heroPrompt: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 25,
    color: COLORS.ink,
  },
  heroMetaLine: {
    marginTop: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.68)",
    fontSize: 12,
    color: "#7A746D",
  },
  caption: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.muted,
  },
  noteCard: {
    backgroundColor: "rgba(255,249,241,0.96)",
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.75)",
  },
  noteEyebrow: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(244,229,206,0.72)",
    fontSize: 11,
    fontWeight: "600",
    color: "#8B735C",
  },
  notePreview: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: "600",
    letterSpacing: -0.2,
    color: COLORS.ink,
  },
  noteThought: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
  },
  noteMeta: {
    fontSize: 13,
    color: "#7A746D",
  },
  emptyState: {
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.ink,
    textAlign: "center",
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
    textAlign: "center",
  },
  primaryButton: {
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 4,
  },
  primaryButtonLabel: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  demoText: {
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.muted,
  },
  errorText: {
    fontSize: 13,
    color: COLORS.danger,
  },
  filterRow: {
    marginHorizontal: -2,
  },
  filterContent: {
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: "rgba(243,228,207,0.84)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.56)",
  },
  filterChipActive: {
    backgroundColor: COLORS.ink,
  },
  filterChipLabel: {
    fontSize: 13,
    color: COLORS.ink,
  },
  filterChipLabelActive: {
    color: "#fff",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  gridItem: {
    width: "47%",
  },
  recentBooksRow: {
    gap: 12,
    paddingRight: 8,
  },
  recentBookCard: {
    width: 164,
    gap: 10,
  },
  recentBookTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.ink,
    letterSpacing: -0.2,
  },
  recentBookAuthor: {
    marginTop: -4,
    fontSize: 13,
    color: COLORS.muted,
  },
  gridTitle: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  gridMeta: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.muted,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionSubhead: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.ink,
  },
  sectionLead: {
    marginTop: -2,
    fontSize: 13,
    lineHeight: 21,
    color: COLORS.muted,
  },
  daysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dayCell: {
    width: "12.5%",
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  dayCellActive: {
    backgroundColor: COLORS.ink,
  },
  dayCellLabel: {
    fontSize: 13,
    color: COLORS.ink,
  },
  dayCellLabelActive: {
    color: "#fff",
  },
  dayCellEmpty: {
    width: "12.5%",
    minWidth: 40,
    height: 42,
  },
  dot: {
    marginTop: 6,
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  dotVisible: {
    backgroundColor: COLORS.accent,
  },
  dotSelected: {
    backgroundColor: "#EBCB96",
  },
  statRow: {
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: "rgba(255,249,241,0.92)",
    borderRadius: 26,
    paddingVertical: 20,
    paddingHorizontal: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    position: "relative",
    overflow: "hidden",
  },
  statCardFeatured: {
    backgroundColor: "rgba(246,232,214,0.96)",
    transform: [{ translateY: -4 }],
  },
  statCardSoft: {
    backgroundColor: "rgba(252,247,239,0.98)",
  },
  statAccentDot: {
    position: "absolute",
    top: 12,
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(209,178,132,0.55)",
  },
  statAccentDotFeatured: {
    backgroundColor: "#D1B284",
  },
  statValue: {
    fontSize: 30,
    fontWeight: "700",
    color: COLORS.ink,
  },
  statValueFeatured: {
    fontSize: 34,
  },
  statLabel: {
    marginTop: 8,
    fontSize: 12,
    color: COLORS.muted,
    textAlign: "center",
  },
  statLabelFeatured: {
    color: "#7D6B56",
  },
  menuRow: {
    backgroundColor: "rgba(255,249,241,0.94)",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 15,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  menuLabel: {
    fontSize: 14,
    color: COLORS.ink,
  },
  menuChevron: {
    fontSize: 24,
    lineHeight: 24,
    color: "#B9AA94",
  },
  logoutChevron: {
    color: "#C8B8A0",
  },
  bottomBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 14,
    backgroundColor: "rgba(255,252,247,0.94)",
    borderRadius: 34,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
    shadowColor: "#CFBFA8",
    shadowOpacity: 0.22,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    borderRadius: 20,
  },
  navButtonActive: {
    backgroundColor: "rgba(243,228,207,0.58)",
  },
  navDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "transparent",
  },
  navDotActive: {
    backgroundColor: "#D1B284",
  },
  navLabel: {
    fontSize: 12,
    color: COLORS.muted,
  },
  navLabelActive: {
    color: COLORS.ink,
    fontWeight: "700",
  },
  plusButton: {
    width: 62,
    height: 62,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.accent,
    marginHorizontal: 4,
    shadowColor: "#143642",
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  plusLabel: {
    fontSize: 28,
    lineHeight: 28,
    color: "#fff",
    fontWeight: "500",
  },
  overlayBackdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 28,
    backgroundColor: "rgba(23,33,43,0.32)",
  },
  overlayCard: {
    maxHeight: "86%",
    backgroundColor: "#fff",
    borderRadius: 34,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  overlayCompact: {
    alignSelf: "center",
    width: "84%",
    maxWidth: 420,
    maxHeight: 210,
    paddingTop: 14,
    paddingBottom: 16,
  },
  overlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  overlayHeaderCentered: {
    justifyContent: "center",
  },
  overlayTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: COLORS.ink,
  },
  overlayTitleCentered: {
    textAlign: "center",
  },
  overlayTitleCompact: {
    fontSize: 18,
    lineHeight: 26,
  },
  overlayContent: {
    gap: 12,
    paddingBottom: 20,
  },
  overlayContentCompact: {
    paddingBottom: 8,
  },
  overlayDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.muted,
  },
  overlayDescriptionCentered: {
    textAlign: "center",
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  input: {
    backgroundColor: COLORS.paper,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 14,
    color: COLORS.ink,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  textarea: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  listGap: {
    gap: 10,
  },
  searchResult: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: COLORS.paper,
    borderRadius: 24,
    padding: 12,
    alignItems: "center",
  },
  searchCoverWrap: {
    width: 86,
  },
  statusRow: {
    backgroundColor: COLORS.paper,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusRowActive: {
    backgroundColor: COLORS.ink,
  },
  statusLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.ink,
  },
  statusLabelActive: {
    color: "#fff",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  primaryInlineButton: {
    flex: 1,
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  secondaryInlineButton: {
    flex: 1,
    backgroundColor: COLORS.paper,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  secondaryInlineLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.ink,
  },
  dangerInlineButton: {
    flex: 1,
    backgroundColor: COLORS.danger,
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  miniActions: {
    flexDirection: "row",
    gap: 14,
    marginTop: 8,
  },
  miniAction: {
    fontSize: 12,
    color: COLORS.muted,
  },
  ratingRow: {
    flexDirection: "row",
    gap: 8,
  },
  ratingButton: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: COLORS.paper,
    alignItems: "center",
    paddingVertical: 12,
  },
  ratingButtonActive: {
    backgroundColor: COLORS.ink,
  },
  ratingLabel: {
    fontSize: 14,
    color: COLORS.ink,
    fontWeight: "600",
  },
  ratingLabelActive: {
    color: "#fff",
  },
  deleteButton: {
    borderWidth: 1,
    borderColor: "#EDC9C9",
    borderRadius: 999,
    alignItems: "center",
    paddingVertical: 14,
  },
  deleteButtonLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.danger,
  },
  toastWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  toast: {
    backgroundColor: COLORS.ink,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  toastLabel: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
});
